
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Redirection API - UNE SEULE FOIS
    location /api/ {
        proxy_pass http://intellistack-chatbot-api:8000/;
        proxy_set_header Host $host;

    }

    # Fichiers statiques
    location / {
        try_files $uri $uri/ /index.html;
    }


}
